### ISSUE TITLE
Cant contact API server

### ISSUE THREAD

**Issue by rakage** [Holfz/de2fa#3]
[GetSteamGuardCode] Can't Contact API Server..
C:\Steam Acc\de2fa\app.js:155
            client.logOff();
            ^

ReferenceError: client is not defined
    at Request._callback (C:\Steam Acc\de2fa\app.js:155:13)
    at Request.self.callback (C:\Steam Acc\de2fa\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Steam Acc\de2fa\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (C:\Steam Acc\de2fa\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by rakage** [comment]
sorry, the email is not from inboxkitten.com. Thats why im getting that error
